import type { SessionSummary } from "../types/core";

/**
 * Utility to convert SessionSummary data into Markdown and handle file downloads.
 */
export class MarkdownExporter {
	/**
	 * Converts a SessionSummary object to a formatted Markdown string.
	 * @param summary The summary to convert
	 * @param transcript Optional full transcript to include
	 * @returns Markdown string
	 */
	convertToMarkdown(summary: SessionSummary, transcript?: string): string {
		const dateStr = summary.generatedAt.toLocaleString();

		let md = `# Session Summary - ${dateStr}\n\n`;
		md += `**Session ID:** \`${summary.sessionId}\`  \n`;
		md += `**Generated At:** ${dateStr}\n\n`;

		md += `## Overall Summary\n${summary.overallSummary}\n\n`;

		if (summary.topics.length > 0) {
			md += "## Topics\n";
			for (const topic of summary.topics) {
				md += `- **${topic.name}** (Relevance: ${(topic.relevance * 100).toFixed(0)}%, Mentions: ${topic.mentions})\n`;
			}
			md += "\n";
		}

		if (summary.insights.length > 0) {
			md += "## AI Insights\n";
			for (const insight of summary.insights) {
				md += `- [${insight.type}] ${insight.content} (Confidence: ${(insight.confidence * 100).toFixed(0)}%)\n`;
			}
			md += "\n";
		}

		if (transcript) {
			md += "## Full Transcript\n";
			md += "```text\n";
			md += transcript;
			md += "\n```\n";
		}

		md += "\n---\n*Generated by MONOLOG LIVE*";

		return md;
	}

	/**
	 * Triggers a browser download of the summary as a Markdown file.
	 * @param summary The summary to export
	 * @param transcript Optional transcript to include
	 */
	downloadAsFile(summary: SessionSummary, transcript?: string): void {
		const markdown = this.convertToMarkdown(summary, transcript);
		const blob = new Blob([markdown], { type: "text/markdown" });
		const url = URL.createObjectURL(blob);

		const filename = `session-summary-${summary.sessionId}-${new Date().toISOString().split("T")[0]}.md`;

		const link = document.createElement("a");
		link.href = url;
		link.download = filename;
		document.body.appendChild(link);
		link.click();

		// Cleanup
		setTimeout(() => {
			document.body.removeChild(link);
			URL.revokeObjectURL(url);
		}, 100);
	}
}
